#!/usr/bin/env python3
"""build-eve-exe.py — package eve.py into dist/EVE/EVE.exe via PyInstaller.

Author: RKOJ-ELENO :: 2026-05-25

Canonical Python successor to the legacy build-eve-exe.bat (kept in place per
no-bat-no-ps1 doctrine "existing .bat files = legacy; new ones banned"). This
script is what session-start-auto-update-propagation doctrine + the iter-23
icon-embed mission want: a Python build runner that:

  1. Ensures pyinstaller is installed (pip-install if missing).
  2. Wipes stale dist/EVE + build/EVE so PyInstaller doesn't trip on a
     non-empty output dir from a prior --onedir run.
  3. Invokes pyinstaller with --onedir, --icon assets/eve-icon.ico, and the
     hidden-import list that eve.py + tools/eve-picker need.
  4. Self-heals Defender quarantine: copies base_library.zip + EVE.exe out of
     build/EVE/ (where they survive because AV scan triggers later) into
     dist/EVE/ if the dist/ copy got wiped mid-COLLECT.
  5. Mirrors the built bundle to %USERPROFILE%\\.eve\\ so the launcher's
     stable-path probe order always lands on a working binary.
  6. Copies the just-built EVE.exe to the repo root (D:\\Sinister Sanctum\\
     EVE.exe) + deploy/EVE.exe so the Leo-handoff folder + sha256 sidecar
     stay in sync with the latest build.

Icon source: automations/eve-launcher/assets/eve-icon.ico. Generated by
make-icon.py from the operator's hero-statement PNG with chroma-key alpha
(no background). If the assets/ copy is missing, fall back to a root-level
eve-icon.ico in the script dir.

Operator hard-canonical 2026-05-24T22:45Z (utterance): "adding the fucking
logo to the exe" — that's why --icon is non-optional here.

Usage:
  python automations/eve-launcher/build-eve-exe.py [--no-mirror] [--no-deploy]

Exit codes:
  0  success
  2  pyinstaller install failed
  3  pyinstaller build failed or dist\\EVE\\EVE.exe missing after build
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SANCTUM_ROOT = HERE.parent.parent
EVE_PY = HERE / "eve.py"
DIST = HERE / "dist"
BUILD = HERE / "build"
DIST_EVE = DIST / "EVE"
BUILD_EVE = BUILD / "EVE"

HIDDEN_IMPORTS = [
    "colorsys",
    "eve_picker_lib",
    "eve_logger",
    "quantum_tools",
    "health_tools",
    "jcode_animation",
    "main_menu",
    "account_manager",
    "account_info_panel",
    "project_picker_multiselect",
    "project_config_grid",
    "tools_menu",
    "eve_ui",
    "garden_of_eden",
]


def info(msg: str) -> None:
    print(f" [build] {msg}")


def warn(msg: str) -> None:
    print(f" [WARN] {msg}")


def fail(msg: str) -> None:
    print(f" [FAIL] {msg}", file=sys.stderr)


def ensure_pyinstaller() -> int:
    try:
        out = subprocess.run(
            [sys.executable, "-m", "PyInstaller", "--version"],
            capture_output=True, text=True, check=False,
        )
        if out.returncode == 0:
            return 0
    except Exception:
        pass
    info("installing pyinstaller via pip...")
    r = subprocess.run(
        [sys.executable, "-m", "pip", "install", "--quiet",
         "--disable-pip-version-check", "pyinstaller"],
        check=False,
    )
    if r.returncode != 0:
        fail("could not install pyinstaller. Run: python -m pip install pyinstaller")
        return 2
    return 0


def resolve_icon() -> Path | None:
    assets_ico = HERE / "assets" / "eve-icon.ico"
    if assets_ico.is_file():
        return assets_ico
    root_ico = HERE / "eve-icon.ico"
    if root_ico.is_file():
        return root_ico
    return None


def wipe(p: Path) -> None:
    if p.exists():
        shutil.rmtree(p, ignore_errors=True)


def run_pyinstaller(icon: Path | None) -> int:
    if DIST_EVE.exists():
        wipe(DIST_EVE)
    if BUILD_EVE.exists():
        wipe(BUILD_EVE)

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--onedir", "--name", "EVE",
        "--distpath", str(DIST),
        "--workpath", str(BUILD),
        "--specpath", str(BUILD),
        "--clean", "--noupx",
        "--paths", str(SANCTUM_ROOT / "tools" / "eve-picker"),
    ]
    if icon is not None:
        cmd += ["--icon", str(icon)]
        info(f"icon -> {icon}")
    else:
        warn("no eve-icon.ico found; building without --icon (run make-icon.py first)")
    for mod in HIDDEN_IMPORTS:
        cmd += ["--hidden-import", mod]
    cmd.append(str(EVE_PY))

    info("packaging eve.py -> dist/EVE/EVE.exe (--onedir)...")
    r = subprocess.run(cmd, cwd=str(HERE), check=False)
    if r.returncode != 0:
        fail("pyinstaller build failed.")
        return 3
    return 0


def self_heal_defender() -> None:
    """Defender sometimes quarantines base_library.zip mid-COLLECT. Salvage
    from build/EVE/ where the file survives because the AV scan triggers
    later than dist/."""
    print()
    info("[self-heal] copying base_library.zip + EVE.exe from build/EVE/ if AV wiped them...")
    internal = DIST_EVE / "_internal"
    internal.mkdir(parents=True, exist_ok=True)
    src_zip = BUILD_EVE / "base_library.zip"
    if src_zip.is_file():
        shutil.copy2(src_zip, internal / "base_library.zip")
        info("[self-heal] base_library.zip restored")
    src_exe = BUILD_EVE / "EVE.exe"
    dst_exe = DIST_EVE / "EVE.exe"
    if src_exe.is_file() and not dst_exe.is_file():
        shutil.copy2(src_exe, dst_exe)
        info("[self-heal] EVE.exe restored from build/")


def mirror_to_stable() -> None:
    stable = Path.home() / ".eve"
    if stable.exists():
        shutil.rmtree(stable, ignore_errors=True)
    stable.mkdir(parents=True, exist_ok=True)
    # Walk dist/EVE and copy everything
    for src in DIST_EVE.rglob("*"):
        rel = src.relative_to(DIST_EVE)
        dst = stable / rel
        if src.is_dir():
            dst.mkdir(parents=True, exist_ok=True)
        else:
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
    # Self-heal mirror too
    src_zip = BUILD_EVE / "base_library.zip"
    if src_zip.is_file():
        (stable / "_internal").mkdir(parents=True, exist_ok=True)
        shutil.copy2(src_zip, stable / "_internal" / "base_library.zip")
    if (stable / "EVE.exe").is_file():
        info(f"[OK] mirrored to {stable / 'EVE.exe'}")
    else:
        warn("stable mirror failed; Sinister Start.bat will fall through to dist.")


def copy_to_repo_and_deploy() -> None:
    dist_exe = DIST_EVE / "EVE.exe"
    if not dist_exe.is_file():
        warn("dist/EVE/EVE.exe missing; cannot copy to repo root.")
        return
    root_exe = SANCTUM_ROOT / "EVE.exe"
    deploy_exe = SANCTUM_ROOT / "deploy" / "EVE.exe"
    deploy_exe.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(dist_exe, root_exe)
    shutil.copy2(dist_exe, deploy_exe)
    info(f"[OK] copied to {root_exe}")
    info(f"[OK] copied to {deploy_exe}")


def regenerate_sha_sidecar() -> None:
    script = SANCTUM_ROOT / "automations" / "build_eve_sha_sidecar.py"
    if script.is_file():
        subprocess.run([sys.executable, str(script)], check=False)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-mirror", action="store_true",
                    help="skip mirror to %USERPROFILE%\\.eve\\")
    ap.add_argument("--no-deploy", action="store_true",
                    help="skip copy to repo root + deploy/")
    ns = ap.parse_args(argv or sys.argv[1:])

    rc = ensure_pyinstaller()
    if rc != 0:
        return rc

    icon = resolve_icon()
    rc = run_pyinstaller(icon)
    if rc != 0:
        return rc

    self_heal_defender()

    dist_exe = DIST_EVE / "EVE.exe"
    if not dist_exe.is_file():
        warn("dist/EVE/EVE.exe missing after build. Check pyinstaller output.")
        return 3

    print()
    info(f"[OK] built {dist_exe}")
    info(f" Test: {dist_exe} --version")

    if not ns.no_mirror:
        mirror_to_stable()
    if not ns.no_deploy:
        copy_to_repo_and_deploy()
        regenerate_sha_sidecar()

    return 0


if __name__ == "__main__":
    sys.exit(main())
