"""Query + recall helpers for the Sinister Jokester intake DB.

Author: RKOJ-ELENO :: 2026-05-26
"""
from __future__ import annotations

import argparse
import json
import sqlite3
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_DB_PATH = REPO_ROOT / "vault" / "db" / "intake.sqlite"
INDEX_MD_PATH = REPO_ROOT / "vault" / "INDEX.md"


def _connect(db_path: Path) -> sqlite3.Connection:
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    return conn


def list_by_verdict(verdict: str | None = None, db_path: Path = DEFAULT_DB_PATH) -> list[dict[str, Any]]:
    with _connect(db_path) as conn:
        if verdict is None:
            rows = conn.execute(
                "SELECT * FROM intake_items ORDER BY intake_ts DESC"
            ).fetchall()
        else:
            rows = conn.execute(
                "SELECT * FROM intake_items WHERE verdict = ? ORDER BY intake_ts DESC",
                (verdict.upper(),),
            ).fetchall()
    return [dict(r) for r in rows]


def search(query: str, db_path: Path = DEFAULT_DB_PATH) -> list[dict[str, Any]]:
    like = f"%{query}%"
    with _connect(db_path) as conn:
        rows = conn.execute(
            """
            SELECT * FROM intake_items
            WHERE source_url LIKE ?
               OR title LIKE ?
               OR short_summary LIKE ?
               OR tags LIKE ?
            ORDER BY intake_ts DESC
            """,
            (like, like, like, like),
        ).fetchall()
    return [dict(r) for r in rows]


def stats(db_path: Path = DEFAULT_DB_PATH) -> dict[str, Any]:
    with _connect(db_path) as conn:
        total = conn.execute("SELECT COUNT(*) AS n FROM intake_items").fetchone()["n"]
        by_verdict = {
            row["verdict"] or "PENDING": row["n"]
            for row in conn.execute(
                "SELECT verdict, COUNT(*) AS n FROM intake_items GROUP BY verdict"
            ).fetchall()
        }
        by_type = {
            row["source_type"]: row["n"]
            for row in conn.execute(
                "SELECT source_type, COUNT(*) AS n FROM intake_items GROUP BY source_type"
            ).fetchall()
        }
    return {"total": total, "by_verdict": by_verdict, "by_type": by_type}


def rebuild_index_md(db_path: Path = DEFAULT_DB_PATH, index_path: Path = INDEX_MD_PATH) -> Path:
    s = stats(db_path)
    items = list_by_verdict(db_path=db_path)
    lines = [
        "# Sinister Jokester — Vault Index",
        "",
        "> Auto-regenerated by `python jokester_cli.py reindex`. Do not hand-edit.",
        "",
        f"**Total items:** {s['total']}",
        "",
        "## Counts",
        "",
        "### By verdict",
        "",
    ]
    if s["by_verdict"]:
        for k, v in sorted(s["by_verdict"].items()):
            lines.append(f"- {k}: {v}")
    else:
        lines.append("- _(none yet)_")
    lines += ["", "### By source type", ""]
    if s["by_type"]:
        for k, v in sorted(s["by_type"].items()):
            lines.append(f"- {k}: {v}")
    else:
        lines.append("- _(none yet)_")

    lines += ["", "## Recent intake (newest first, top 25)", ""]
    if items:
        for it in items[:25]:
            verdict = it.get("verdict") or "PENDING"
            md_path = it.get("decision_md_path") or "-"
            title = it.get("title") or it.get("source_url")
            lines.append(
                f"- `{it['id']}` :: **{verdict}** :: [{title}]({it['source_url']}) :: md=`{md_path}`"
            )
    else:
        lines.append("- _(empty corpus — run `python jokester_cli.py intake <url>` to seed)_")
    lines.append("")
    index_path.write_text("\n".join(lines), encoding="utf-8")
    return index_path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Recall + query helpers for the Jokester intake DB.")
    parser.add_argument("--db", type=Path, default=DEFAULT_DB_PATH)
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_list = sub.add_parser("list", help="List items, optionally filtered by verdict.")
    p_list.add_argument("--verdict", choices=["adopt", "watch", "reject"], default=None)

    p_search = sub.add_parser("search", help="Free-text search across url/title/summary/tags.")
    p_search.add_argument("query")

    sub.add_parser("stats", help="Counts by verdict + source type.")
    sub.add_parser("rebuild-index", help="Rewrite vault/INDEX.md from DB state.")

    args = parser.parse_args(argv)

    if args.cmd == "list":
        out = list_by_verdict(args.verdict.upper() if args.verdict else None, args.db)
        print(json.dumps(out, indent=2, default=str))
    elif args.cmd == "search":
        out = search(args.query, args.db)
        print(json.dumps(out, indent=2, default=str))
    elif args.cmd == "stats":
        print(json.dumps(stats(args.db), indent=2))
    elif args.cmd == "rebuild-index":
        path = rebuild_index_md(args.db)
        print(f"ok index={path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
