@echo off
REM Auto-generated by sanctum_schtask_hide_wrap.py (F2)
REM Wraps long original-exec for: \SinisterOverseerContradictionWeeklyDigest
cmd /c set "PYTHONPATH=D:\Sinister Sanctum\projects\sinister-overseer\src" && "C:\Users\Zonia\AppData\Local\Programs\Python\Python312\python.exe" -m overseer contradiction-pass --weekly-digest
