#!/usr/bin/env bash
# apply.sh — writes a chosen corpus fingerprint into the next cvd boot
# RKOJ-ELENO :: 2026-05-24
#
# cvd lets you inject extra setprop calls into the boot via --extra_kernel_cmdline
# (for kernel-level) and via a setup script that runs in init.d. We use the
# init.d path because the device-class props (build_fingerprint, lock state,
# verified-boot) are userspace concerns, not kernel.
#
# Usage:
#   bash apply.sh --class cvd_clean
#   bash apply.sh --class physical_locked --json   # JSON output for the harness
#
# Note: cuttlefish doesn't perfectly honor setprop overrides for read-only
# system props baked into /system/build.prop; some props are immutable after
# init reads them. This script writes the overrides + flags which props
# took effect via getprop verification.

set -euo pipefail

WORKDIR="${SINISTER_CVD_HOME:-$HOME/sinister-cvd}"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
CORPUS="$SCRIPT_DIR/corpus.json"
JSON_OUT=0
CLASS=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --class) CLASS="$2"; shift 2 ;;
    --json)  JSON_OUT=1; shift ;;
    -h|--help) echo "Usage: $0 --class <class_name> [--json]"; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 1 ;;
  esac
done

[[ -n "$CLASS" ]] || { echo "FAIL: --class required" >&2; exit 1; }
[[ -f "$CORPUS" ]] || { echo "FAIL: corpus.json missing at $CORPUS — run generate.py first" >&2; exit 1; }
command -v jq >/dev/null || { echo "FAIL: jq required" >&2; exit 1; }

# Pick the first matching row of that class
ROW="$(jq -c --arg c "$CLASS" 'map(select(.class_name == $c)) | .[0]' "$CORPUS")"
[[ "$ROW" != "null" ]] || { echo "FAIL: class '$CLASS' not in corpus" >&2; exit 2; }

# Extract props to write
BUILD_FP="$(echo "$ROW" | jq -r .build_fingerprint)"
MODEL="$(echo "$ROW" | jq -r .product_model)"
LOCKED="$(echo "$ROW" | jq -r .bootloader_locked)"
VBSTATE="$(echo "$ROW" | jq -r .verified_boot)"
DEVOPTS="$(echo "$ROW" | jq -r .developer_options)"
DEVICE_ID="$(echo "$ROW" | jq -r .device_id)"

# Write the per-boot override script
OVR="$WORKDIR/cvd-boot-overrides.sh"
cat > "$OVR" <<EOF
#!/system/bin/sh
# Generated by sandbox/fingerprints/apply.sh for class '$CLASS' (device $DEVICE_ID)
# Will be pushed to /data/local/tmp/cvd-boot-overrides.sh + invoked via adb on next boot.
setprop persist.sinister.class "$CLASS"
setprop persist.sinister.device_id "$DEVICE_ID"
settings put global development_settings_enabled $DEVOPTS
# Note: ro.build.fingerprint / ro.boot.flash.locked are immutable after init.
# Document the EXPECTED value here so the boot-check.sh diff catches mismatches.
echo "expected build_fingerprint: $BUILD_FP" > /data/local/tmp/cvd-expected.txt
echo "expected bootloader_locked: $LOCKED" >> /data/local/tmp/cvd-expected.txt
echo "expected verified_boot: $VBSTATE" >> /data/local/tmp/cvd-expected.txt
EOF
chmod +x "$OVR"

if [[ "$JSON_OUT" == "1" ]]; then
  jq -n --argjson row "$ROW" --arg path "$OVR" \
    '{status: "ok", class: $row.class_name, device_id: $row.device_id, overrides_path: $path}'
else
  echo "[apply] picked class=$CLASS device_id=$DEVICE_ID"
  echo "[apply] overrides script: $OVR"
  echo "[apply] expected props: build_fp=$BUILD_FP locked=$LOCKED vb=$VBSTATE dev_opts=$DEVOPTS"
  echo "[apply] next: bash scripts/boot-cuttlefish.sh   # boot will pick up the overrides"
fi
