# Author: RKOJ-ELENO :: 2026-05-23
# Sanctum :: cross-lane impact diff (C.6 of sanctum-complete-and-expand master plan)
#
# When a commit touches shared/canonical files (projects.json, CLAUDE.md,
# settings.json, .gitignore, _INDEX.md, OPERATOR-ACTION-QUEUE.md), emit a
# cross-agent broadcast to _shared-memory/cross-agent/<UTC>-<from>-impact.md
# so sibling lanes see the change BEFORE they sync + can react.
#
# Trigger modes:
#   - manual: ps1 -Range HEAD~1..HEAD          (default: last commit)
#   - post-commit hook: ps1 -Hook              (reads ORIG_HEAD..HEAD)
#   - dry-run: ps1 -DryRun                     (preview message, no file write)
#
# Smoke test: .\cross-lane-impact-diff.ps1 -DryRun -Verbose

[CmdletBinding()]
param(
    [string]$SanctumRoot = "D:\Sinister Sanctum",
    [string]$Range = "HEAD~1..HEAD",
    [string]$From = "sanctum",
    [switch]$Hook,
    [switch]$DryRun
)

if ($Hook) { $Range = "ORIG_HEAD..HEAD" }

# Shared canonical files that warrant a cross-lane broadcast
$canonicalFiles = @(
    'automations/session-templates/projects.json',
    'automations/session-templates/agent-prefs.json',
    'CLAUDE.md',
    '.claude/settings.json',
    '.claude/settings.local.json',
    '.gitignore',
    '_shared-memory/knowledge/_INDEX.md',
    '_shared-memory/OPERATOR-ACTION-QUEUE.md',
    '_shared-memory/DIRECTIVES.md',
    '_shared-memory/WORK-TOWARD.md',
    '_shared-memory/WORKSTATION.md',
    'SESSION-START/00-RULES.md',
    'automations/canonical-protections-check.ps1',
    'automations/start-sinister-session.ps1',
    'automations/grant-claude-autonomy.ps1'
)

Push-Location $SanctumRoot
try {
    $changed = & git diff --name-only $Range 2>$null
    if (-not $changed) {
        Write-Verbose "No files in range $Range"
        return
    }
    $impactedCanonical = @()
    foreach ($f in $changed) {
        $f = $f -replace '\\','/'
        if ($canonicalFiles -contains $f) { $impactedCanonical += $f }
    }
    if ($impactedCanonical.Count -eq 0) {
        Write-Verbose "No canonical files in this range - no broadcast needed."
        return
    }

    $headCommit = (& git rev-parse --short HEAD 2>$null).Trim()
    $headMsg = (& git log -1 --pretty=%s HEAD 2>$null).Trim()
    $branch = (& git rev-parse --abbrev-ref HEAD 2>$null).Trim()
    $tsUtc = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHHmmZ")
    $tsDir = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHHmmssZ")

    # Build body via simple concatenation (avoids here-string + backtick escape pain)
    $nl = [Environment]::NewLine
    $bt3 = '```'
    $body = ''
    $body += "<!-- Author: RKOJ-ELENO :: $(Get-Date -Format 'yyyy-MM-dd') -->$nl"
    $body += "# Cross-Lane Impact :: lane '$From' touched $($impactedCanonical.Count) canonical file(s)$nl$nl"
    $body += "**Origin:** lane '$From' on branch '$branch' / commit '$headCommit'$nl"
    $body += "**Subject:** '$headMsg'$nl"
    $body += "**Timestamp:** $tsUtc UTC$nl"
    $body += "**Range:** '$Range'$nl$nl"
    $body += "## Why every lane should care$nl$nl"
    $body += "The files below are fleet-shared. Your next 'git pull' will pull these changes$nl"
    $body += "into your working tree. Read this before you 'git pull' so the diff doesn't$nl"
    $body += "surprise mid-turn.$nl$nl"
    $body += "## Canonical files impacted$nl$nl"

    foreach ($f in $impactedCanonical) {
        $stat = & git diff --stat $Range -- $f 2>$null | Select-Object -First 1
        $body += "- '$f'"
        if ($stat) { $body += "  $($stat.Trim())" }
        $body += $nl
    }

    $body += "$nl## Quick diff (first 40 lines)$nl$nl"
    $body += "${bt3}diff$nl"
    $diff = & git diff $Range -- $impactedCanonical 2>$null | Select-Object -First 40
    $body += ($diff -join $nl)
    $body += "$nl${bt3}$nl$nl"

    $body += "## Recommended action (per lane)$nl$nl"
    $body += "- Read the diff above before next 'git pull'$nl"
    $body += "- If you have un-committed work in your lane: 'git stash' then 'git pull' then 'git stash pop' to merge cleanly$nl"
    $body += "- If your lane's CLAUDE.md / settings.json depend on the changed file: re-run 'automations/canonical-protections-check.ps1' after pull$nl"
    $body += "- This broadcast was generated by 'automations/cross-lane-impact-diff.ps1' (C.6)$nl"

    # Write the broadcast file
    $outDir = Join-Path $SanctumRoot "_shared-memory\cross-agent"
    if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }
    $outName = "${tsDir}-${From}-canonical-impact.md"
    $outPath = Join-Path $outDir $outName

    if ($DryRun) {
        Write-Host "=== DRY RUN: would write $outPath ==="
        Write-Host $body
    } else {
        # BOM-free UTF-8 (PowerShell 5.1 Set-Content -Encoding UTF8 writes BOM)
        [System.IO.File]::WriteAllText($outPath, $body, [System.Text.UTF8Encoding]::new($false))
        Write-Host "[cross-lane-impact-diff] wrote $outPath"
        Write-Host "  files: $($impactedCanonical.Count) canonical"
        Write-Host "  commit: $headCommit ($headMsg)"
    }
} finally {
    Pop-Location
}
exit 0
