# Author: Sinister Sanctum master agent (Claude) :: 2026-05-19
"""
tools/new-tile.py — RKOJ.exe ribbon-tile + pane scaffold

Every time we add a new ribbon tile + pane to RKOJ, we touch four files:
  server.py            - FastAPI route stub
  web/index.html       - <template id="tpl-<id>"> + ribbon button slot
  web/app.js           - WINDOW_TOOLS_REGISTRY entry + PaneRegistry handler stub
  web/theme.css        - per-pane scoped styles (.<id>-pane { ... })

This script emits all four patches in one shot. Run interactively (asks for
each field via input()) or pass --id/--label/--icon/--group/--type/--route
for non-interactive mode. Default is dry-run (print to stdout). Pass
--apply to write patches to disk.

USAGE
-----
  Dry-run (prints 4 patches to stdout):
    python tools/new-tile.py --id codex-review --label "Codex review" \
        --icon "shield" --group SPAWN --type drawer --route /api/codex/review

  Apply (writes to the 4 files in-place, idempotently):
    python tools/new-tile.py --apply --id my-tile --label "My Tile" ...

Idempotent: if tpl-<id> already exists in index.html the HTML patch is
skipped + a warning is printed. Other patches are best-effort.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Optional

SANCTUM_ROOT = Path(r"D:\Sinister Sanctum")
WM_ROOT = SANCTUM_ROOT / "automations" / "window-manager"
WEB_ROOT = WM_ROOT / "web"

SERVER_PY = WM_ROOT / "server.py"
INDEX_HTML = WEB_ROOT / "index.html"
APP_JS = WEB_ROOT / "app.js"
THEME_CSS = WEB_ROOT / "theme.css"

AUTHOR_LINE = "# Author: Sinister Sanctum master agent (Claude) :: 2026-05-19"
JS_AUTHOR_LINE = "// Author: Sinister Sanctum master agent (Claude) :: 2026-05-19"
HTML_AUTHOR_LINE = "<!-- Author: Sinister Sanctum master agent (Claude) :: 2026-05-19 -->"
CSS_AUTHOR_LINE = "/* Author: Sinister Sanctum master agent (Claude) :: 2026-05-19 */"

VALID_GROUPS = {"VIEW", "SPAWN", "AUTOMATE", "MAINTAIN"}
VALID_TYPES = {"drawer", "fullpane", "popover"}


# ---- prompt helpers --------------------------------------------------------

def _ask(prompt: str, default: Optional[str] = None) -> str:
    suffix = f" [{default}]" if default else ""
    raw = input(f"{prompt}{suffix}: ").strip()
    if not raw and default is not None:
        return default
    return raw


def _ask_choice(prompt: str, choices: set[str], default: Optional[str] = None) -> str:
    while True:
        v = _ask(f"{prompt} ({'/'.join(sorted(choices))})", default)
        if v in choices:
            return v
        print(f"  invalid - pick one of {sorted(choices)}")


def _slug_ok(s: str) -> bool:
    if not s:
        return False
    if s != s.lower():
        return False
    for c in s:
        if not (c.isalnum() or c == "-"):
            return False
    return True


# ---- patch builders --------------------------------------------------------

def _patch_server(tile_id: str, route: str) -> str:
    """FastAPI route stub. Caller picks insertion point (before
    `if __name__ == "__main__":`)."""
    fn = tile_id.replace("-", "_") + "_handler"
    route = route if route.startswith("/") else "/" + route
    return (
        f"\n\n# ---- [scaffold] {tile_id} route stub --------------------------------------\n"
        f"# Generated by tools/new-tile.py. Replace with real implementation.\n"
        f"@app.get({route!r})\n"
        f"def {fn}():\n"
        f'    """[scaffold] tile={tile_id!r} - replace with real implementation."""\n'
        f"    return {{'ok': True, 'stub': True, 'tile': {tile_id!r}}}\n"
    )


def _patch_index_html(tile_id: str, label: str, icon: str) -> str:
    """<template id="tpl-<id>"> block. Caller inserts before the closing
    </body> tag (or before the last </template> if present)."""
    safe_icon = icon.strip() or "*"
    return (
        f"\n    {HTML_AUTHOR_LINE}\n"
        f'    <template id="tpl-{tile_id}">\n'
        f'        <div class="lg-card {tile_id}-pane" data-pane="{tile_id}">\n'
        f'            <div class="pane-header">\n'
        f'                <h2><span class="rkoj-tile-icon">{safe_icon}</span> {label}</h2>\n'
        f'                <span class="count" data-bind="{tile_id}-count">0</span>\n'
        f'            </div>\n'
        f'            <div class="empty-note" data-bind="{tile_id}-body">\n'
        f'                [scaffold] {label} pane - replace this content via PaneRegistry.{tile_id}\n'
        f'            </div>\n'
        f'        </div>\n'
        f"    </template>\n"
    )


def _patch_app_js(tile_id: str, label: str, icon: str, group: str, pane_type: str, route: str) -> str:
    """Push to WINDOW_TOOLS_REGISTRY + register a PaneRegistry handler.
    Caller appends this anywhere AFTER both registries exist."""
    safe_icon = icon.strip() or "*"
    safe_route = route if route.startswith("/") else "/" + route
    return (
        f"\n{JS_AUTHOR_LINE}\n"
        f"// [scaffold] {tile_id} - generated by tools/new-tile.py.\n"
        f"// Group: {group} :: Type: {pane_type} :: Route: {safe_route}\n"
        f"(function () {{\n"
        f"    if (typeof window === 'undefined') return;\n"
        f"    // Append to ribbon tools registry (graceful if the registry hasn't been created).\n"
        f"    try {{\n"
        f"        if (typeof WINDOW_TOOLS_REGISTRY !== 'undefined' && Array.isArray(WINDOW_TOOLS_REGISTRY)) {{\n"
        f"            WINDOW_TOOLS_REGISTRY.push({{\n"
        f"                id: {tile_id!r},\n"
        f"                label: {label!r},\n"
        f"                icon: {safe_icon!r},\n"
        f"                group: {group!r},\n"
        f"                paneType: {pane_type!r},\n"
        f"                route: {safe_route!r},\n"
        f"            }});\n"
        f"        }}\n"
        f"    }} catch (e) {{ /* registry missing - skip */ }}\n"
        f"    // Register a Pane handler.\n"
        f"    try {{\n"
        f"        if (typeof PaneRegistry !== 'undefined') {{\n"
        f"            PaneRegistry[{tile_id!r}] = {{\n"
        f"                mount: function (host) {{\n"
        f"                    // [scaffold] wire DOM events here.\n"
        f"                }},\n"
        f"                refresh: async function (host) {{\n"
        f"                    // [scaffold] fetch {safe_route} and render into host.\n"
        f"                    try {{\n"
        f"                        const r = await fetch({safe_route!r});\n"
        f"                        const j = await r.json();\n"
        f"                        const body = host && host.querySelector ? host.querySelector('[data-bind=\"{tile_id}-body\"]') : null;\n"
        f"                        if (body) body.textContent = JSON.stringify(j);\n"
        f"                    }} catch (e) {{ /* silent */ }}\n"
        f"                }},\n"
        f"            }};\n"
        f"        }}\n"
        f"    }} catch (e) {{ /* PaneRegistry missing - skip */ }}\n"
        f"    // Cmd+K palette entry.\n"
        f"    try {{\n"
        f"        if (window.RkojPalette && window.RkojPalette.registerRibbonAction) {{\n"
        f"            window.RkojPalette.registerRibbonAction({{\n"
        f"                id: 'tile:{tile_id}',\n"
        f"                label: 'Open {label} pane',\n"
        f"                icon: {safe_icon!r},\n"
        f"                category: {group!r},\n"
        f"                handler: function () {{\n"
        f"                    try {{ window.dispatchEvent(new CustomEvent('rkoj:open-tile', {{ detail: {{ id: {tile_id!r} }} }})); }} catch (e) {{}}\n"
        f"                }},\n"
        f"            }});\n"
        f"        }}\n"
        f"    }} catch (e) {{ /* palette missing - skip */ }}\n"
        f"}})();\n"
    )


def _patch_theme_css(tile_id: str, label: str) -> str:
    """Scoped styles for the new pane. Caller appends to end of theme.css."""
    return (
        f"\n{CSS_AUTHOR_LINE}\n"
        f"/* [scaffold] {tile_id} pane - generated by tools/new-tile.py. {label} */\n"
        f".{tile_id}-pane {{\n"
        f"    display: flex;\n"
        f"    flex-direction: column;\n"
        f"    gap: 12px;\n"
        f"    padding: 16px 18px;\n"
        f"}}\n"
        f".{tile_id}-pane .pane-header {{\n"
        f"    display: flex;\n"
        f"    align-items: baseline;\n"
        f"    justify-content: space-between;\n"
        f"    border-bottom: 1px solid var(--hairline, rgba(255, 255, 255, 0.06));\n"
        f"    padding-bottom: 8px;\n"
        f"}}\n"
        f".{tile_id}-pane .pane-header h2 {{\n"
        f"    margin: 0;\n"
        f"    font-size: 15px;\n"
        f"    color: var(--text-primary, #fff);\n"
        f"}}\n"
        f".{tile_id}-pane .empty-note {{\n"
        f"    color: var(--text-tertiary, #71717a);\n"
        f"    font-size: 12px;\n"
        f"    padding: 18px 8px;\n"
        f"}}\n"
    )


# ---- apply helpers ---------------------------------------------------------

def _insert_before(text: str, marker: str, insert: str) -> tuple[str, bool]:
    """Insert `insert` immediately before `marker` in `text`. Returns (new_text, found)."""
    idx = text.rfind(marker)
    if idx < 0:
        return text + insert, False
    return text[:idx] + insert + text[idx:], True


def _apply_server(patch: str, tile_id: str) -> str:
    if not SERVER_PY.exists():
        return f"[skip] {SERVER_PY} not found"
    txt = SERVER_PY.read_text(encoding="utf-8")
    if f"tile={tile_id!r}" in txt or f"def {tile_id.replace('-', '_')}_handler" in txt:
        return f"[skip] {SERVER_PY.name}: route stub already present"
    # Insert before "if __name__ ==" or end-of-file.
    new, found = _insert_before(txt, 'if __name__ == "__main__":', patch)
    if not found:
        new, _ = _insert_before(txt, "if __name__ == '__main__':", patch)
    SERVER_PY.write_text(new, encoding="utf-8")
    return f"[ok] {SERVER_PY.name}: appended route stub"


def _apply_index_html(patch: str, tile_id: str) -> str:
    if not INDEX_HTML.exists():
        return f"[skip] {INDEX_HTML} not found"
    txt = INDEX_HTML.read_text(encoding="utf-8")
    if f'id="tpl-{tile_id}"' in txt:
        return f"[skip] {INDEX_HTML.name}: tpl-{tile_id} already exists"
    # Insert before the first <script> tag (templates live before scripts).
    idx = txt.rfind("<script ")
    if idx < 0:
        idx = txt.rfind("</body>")
    if idx < 0:
        INDEX_HTML.write_text(txt + patch, encoding="utf-8")
        return f"[ok] {INDEX_HTML.name}: appended template (no insertion anchor)"
    new = txt[:idx] + patch + "\n    " + txt[idx:]
    INDEX_HTML.write_text(new, encoding="utf-8")
    return f"[ok] {INDEX_HTML.name}: inserted tpl-{tile_id} before <script>"


def _apply_app_js(patch: str, tile_id: str) -> str:
    if not APP_JS.exists():
        return f"[skip] {APP_JS} not found"
    txt = APP_JS.read_text(encoding="utf-8")
    if f"id: {tile_id!r}" in txt or f"PaneRegistry[{tile_id!r}]" in txt:
        return f"[skip] {APP_JS.name}: handler already present"
    APP_JS.write_text(txt.rstrip() + "\n" + patch, encoding="utf-8")
    return f"[ok] {APP_JS.name}: appended PaneRegistry + tile + palette entry"


def _apply_theme_css(patch: str, tile_id: str) -> str:
    if not THEME_CSS.exists():
        return f"[skip] {THEME_CSS} not found"
    txt = THEME_CSS.read_text(encoding="utf-8")
    if f".{tile_id}-pane" in txt:
        return f"[skip] {THEME_CSS.name}: .{tile_id}-pane already present"
    THEME_CSS.write_text(txt.rstrip() + "\n" + patch, encoding="utf-8")
    return f"[ok] {THEME_CSS.name}: appended pane styles"


# ---- main ------------------------------------------------------------------

def _collect_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        prog="new-tile.py",
        description="Scaffold a new RKOJ.exe ribbon tile + pane (4-file patch).",
    )
    p.add_argument("--id", dest="tile_id", help="lowercase-with-dashes (e.g. codex-review)")
    p.add_argument("--label", help="display label (e.g. 'Codex review')")
    p.add_argument("--icon", help="single emoji, glyph, or inline SVG")
    p.add_argument("--group", help=f"ribbon group: {sorted(VALID_GROUPS)}")
    p.add_argument("--type", dest="pane_type", help=f"pane type: {sorted(VALID_TYPES)}")
    p.add_argument("--route", help="API route slug (e.g. /api/foo)")
    p.add_argument("--apply", action="store_true",
                   help="WRITE patches to disk (default: print to stdout)")
    p.add_argument("--dry-run", action="store_true",
                   help="verbose dry-run (same as default print mode)")
    return p.parse_args()


def main() -> int:
    args = _collect_args()

    # Interactive fallback for any missing fields.
    tile_id = args.tile_id
    while not tile_id or not _slug_ok(tile_id):
        if tile_id:
            print(f"  invalid id {tile_id!r} - lowercase letters/digits/dashes only")
        tile_id = _ask("Tile id (lowercase-with-dashes)")

    label = args.label or _ask("Display label", default=tile_id.replace("-", " ").title())
    icon = args.icon or _ask("Tile icon (emoji or short SVG)", default="*")
    group = args.group or _ask_choice("Ribbon group", VALID_GROUPS, default="SPAWN")
    if group not in VALID_GROUPS:
        print(f"  invalid group {group!r} - must be one of {sorted(VALID_GROUPS)}")
        return 1

    pane_type = args.pane_type or _ask_choice("Pane type", VALID_TYPES, default="drawer")
    if pane_type not in VALID_TYPES:
        print(f"  invalid type {pane_type!r} - must be one of {sorted(VALID_TYPES)}")
        return 1

    route = args.route or _ask("API route slug", default=f"/api/{tile_id}")
    if not route.startswith("/"):
        route = "/" + route

    patches = {
        "server.py": _patch_server(tile_id, route),
        "web/index.html": _patch_index_html(tile_id, label, icon),
        "web/app.js": _patch_app_js(tile_id, label, icon, group, pane_type, route),
        "web/theme.css": _patch_theme_css(tile_id, label),
    }

    if args.apply:
        results = [
            _apply_server(patches["server.py"], tile_id),
            _apply_index_html(patches["web/index.html"], tile_id),
            _apply_app_js(patches["web/app.js"], tile_id),
            _apply_theme_css(patches["web/theme.css"], tile_id),
        ]
        print(f"\n[new-tile.py] APPLY mode :: tile_id={tile_id} group={group} type={pane_type}")
        for r in results:
            print("  " + r)
        return 0

    # dry-run (default)
    verbose = args.dry_run or True
    print(f"\n[new-tile.py] DRY-RUN :: tile_id={tile_id} group={group} type={pane_type} route={route}")
    print(f"  label={label!r} icon={icon!r}")
    print(f"  4 patches generated. Re-run with --apply to write to disk.\n")
    for fname, patch in patches.items():
        sep = "=" * 60
        print(f"\n{sep}\n  PATCH :: {fname}\n{sep}")
        if verbose:
            print(patch)
        else:
            preview = patch.strip().splitlines()[:5]
            for line in preview:
                print("  " + line)
            print(f"  ... ({len(patch.splitlines())} lines total)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
